2015-08-10 09:24:51 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-08-10 09:25:58 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-08-10 09:27:35 Error: Fatal Error (64): Cannot redeclare class PostsController in [/private/var/www/apps/blog/Controller/PostsController.php, line 6]
2015-08-10 09:27:35 Error: [FatalErrorException] Cannot redeclare class PostsController
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', '/private/var/ww...', 6)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', '/private/var/ww...', 6, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', '/private/var/ww...', 6, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 09:28:27 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 7]
2015-08-10 09:28:27 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 7)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 7, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 7, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 09:29:29 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-08-10 09:31:01 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /Posts/index
Stack Trace:
#0 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-08-10 09:31:47 Error: [MissingActionException] Action PostsController::view() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'view',
)
Request URL: /posts/view/1
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-08-10 09:36:19 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 10]
2015-08-10 09:36:19 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /Posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 10)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 10, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 10, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 09:37:05 Error: [MissingViewException] View file "Posts/view.ctp" is missing.
Exception Attributes: array (
  'file' => 'Posts/view.ctp',
)
Request URL: /posts/view/1
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName(NULL)
#1 /private/var/www/frameworks/cakephp/lib/Cake/Controller/Controller.php(960): View->render(NULL, NULL)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-08-10 09:39:09 Error: Fatal Error (4): syntax error, unexpected '[', expecting ')' in [/private/var/www/apps/blog/View/Posts/view.ctp, line 9]
2015-08-10 09:39:09 Error: [FatalErrorException] syntax error, unexpected '[', expecting ')'
Request URL: /posts/view/1
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 9)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 9, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 9, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:36:11 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 55]
2015-08-10 10:36:11 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 55, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 55, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:37:01 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [/private/var/www/apps/blog/Controller/PostsController.php, line 73]
2015-08-10 10:37:01 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 73)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 73, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 73, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:37:31 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [/private/var/www/apps/blog/Controller/PostsController.php, line 72]
2015-08-10 10:37:31 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 72)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 72, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 72, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:37:31 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [/private/var/www/apps/blog/Controller/PostsController.php, line 72]
2015-08-10 10:37:31 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 72)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 72, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 72, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:38:51 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [/private/var/www/apps/blog/Controller/PostsController.php, line 50]
2015-08-10 10:38:51 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 50)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 50, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 50, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:39:20 Error: Fatal Error (4): syntax error, unexpected end of file in [/private/var/www/apps/blog/Controller/PostsController.php, line 47]
2015-08-10 10:39:20 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 47, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 47, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:40:02 Error: [MissingActionException] Action PostsController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'edit',
)
Request URL: /posts/edit/7
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-08-10 10:40:13 Error: [MissingActionException] Action PostsController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'edit',
)
Request URL: /posts/edit/3
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-08-10 10:41:12 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 55]
2015-08-10 10:41:12 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 55, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 55, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:42:02 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 33]
2015-08-10 10:42:02 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 33)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 33, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 33, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:42:04 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 33]
2015-08-10 10:42:04 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 33)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 33, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 33, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:42:29 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 61]
2015-08-10 10:42:29 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 61)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 61, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 61, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:42:30 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 61]
2015-08-10 10:42:30 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 61)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 61, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 61, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:43:00 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 53]
2015-08-10 10:43:00 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 53)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 53, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 53, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:43:02 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 53]
2015-08-10 10:43:02 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 53)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 53, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 53, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:43:30 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [/private/var/www/apps/blog/Controller/PostsController.php, line 53]
2015-08-10 10:43:30 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 53)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 53, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 53, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:43:46 Error: Fatal Error (4): syntax error, unexpected end of file in [/private/var/www/apps/blog/Controller/PostsController.php, line 53]
2015-08-10 10:43:46 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 53)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 53, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 53, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:44:10 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [/private/var/www/apps/blog/Controller/PostsController.php, line 54]
2015-08-10 10:44:10 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 54)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 54, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 54, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:45:05 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [/private/var/www/apps/blog/Controller/PostsController.php, line 55]
2015-08-10 10:45:05 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /posts
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 55, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 55, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:45:19 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [/private/var/www/apps/blog/Controller/PostsController.php, line 55]
2015-08-10 10:45:19 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /posts/add
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 55, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 55, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:45:19 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [/private/var/www/apps/blog/Controller/PostsController.php, line 55]
2015-08-10 10:45:19 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 55)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 55, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 55, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:46:07 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 54]
2015-08-10 10:46:07 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 54)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 54, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 54, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:47:11 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 54]
2015-08-10 10:47:11 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 54)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 54, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 54, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 10:47:48 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/private/var/www/apps/blog/Controller/PostsController.php, line 54]
2015-08-10 10:47:48 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /posts/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/private/var/ww...', 54)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/private/var/ww...', 54, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/private/var/ww...', 54, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:12:45 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-10 11:12:45 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:12:55 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-10 11:12:55 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:15:17 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-10 11:15:17 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:15:25 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-10 11:15:25 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users/add
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:17:21 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-10 11:17:21 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Users/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:25:51 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-10 11:25:51 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Users/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:26:02 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-10 11:26:02 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Users/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:26:09 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-10 11:26:09 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Users/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:26:13 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-10 11:26:13 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Users/index
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:26:13 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-10 11:26:13 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /Users
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-10 11:28:40 Error: [MissingControllerException] Controller class Apple-touch-icon-precomposed.pngController could not be found.
Exception Attributes: array (
  'class' => 'Apple-touch-icon-precomposed.pngController',
  'plugin' => NULL,
)
Request URL: /apple-touch-icon-precomposed.png
Stack Trace:
#0 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-08-10 11:28:40 Error: [MissingControllerException] Controller class Apple-touch-icon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Apple-touch-icon.pngController',
  'plugin' => NULL,
)
Request URL: /apple-touch-icon.png
Stack Trace:
#0 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-08-12 13:32:57 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-12 13:32:57 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users/add
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-12 13:32:58 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-12 13:32:58 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-12 13:32:59 Error: Fatal Error (1): Call to a member function allow() on a non-object in [/private/var/www/apps/blog/Controller/UsersController.php, line 8]
2015-08-12 13:32:59 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /users/add
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/private/var/ww...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/private/var/ww...', 8, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-12 13:42:51 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-08-12 13:56:00 Error: Fatal Error (64): Cannot redeclare UsersController::beforeFilter() in [/private/var/www/apps/blog/Controller/UsersController.php, line 74]
2015-08-12 13:56:00 Error: [FatalErrorException] Cannot redeclare UsersController::beforeFilter()
Request URL: /users/login
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', '/private/var/ww...', 74)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', '/private/var/ww...', 74, Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', '/private/var/ww...', 74, Array)
#3 /private/var/www/frameworks/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-08-12 13:56:32 Error: [MissingViewException] View file "Users/login.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users/login.ctp',
)
Request URL: /users/login
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName(NULL)
#1 /private/var/www/frameworks/cakephp/lib/Cake/Controller/Controller.php(960): View->render(NULL, NULL)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-08-12 13:56:40 Error: [MissingViewException] View file "Users/login.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users/login.ctp',
)
Request URL: /users/login
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName(NULL)
#1 /private/var/www/frameworks/cakephp/lib/Cake/Controller/Controller.php(960): View->render(NULL, NULL)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-08-12 13:59:42 Error: [MissingViewException] View file "Users/login.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users/login.ctp',
)
Request URL: /users/login
Stack Trace:
#0 /private/var/www/frameworks/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName(NULL)
#1 /private/var/www/frameworks/cakephp/lib/Cake/Controller/Controller.php(960): View->render(NULL, NULL)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-08-12 14:08:13 Error: [NotFoundException] Invalid user
Request URL: /users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 /private/var/www/frameworks/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-08-12 14:08:17 Error: [NotFoundException] Invalid user
Request URL: /users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 /private/var/www/frameworks/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-08-12 14:26:11 Error: [NotFoundException] Invalid user
Request URL: /users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 /private/var/www/frameworks/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-08-12 14:26:16 Error: [NotFoundException] Invalid user
Request URL: /users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 /private/var/www/frameworks/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /private/var/www/frameworks/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /private/var/www/apps/blog/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
